- platform: gree
  # required settings:
  name: First AC
  host: <ip of your first AC>
  mac: '<mac address of your first AC>'
  # optional settings:
  port: 7000
  timeout: 10
  target_temp_step: 1

- platform: gree
  # required settings:
  name: Second AC
  host: <ip of your second AC>
  mac: '<mac address of your second AC>'
  # optional settings:
  port: 7000
  timeout: 10
  target_temp_step: 1
